name: wireguard_dart
description: Wireguard Dart SDK
version: 0.4.4
homepage: https://github.com/mysteriumnetwork/wireguard_dart
repository: https://github.com/mysteriumnetwork/wireguard_dart

environment:
  sdk: '^3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: network.mysterium.wireguard_dart
        pluginClass: WireguardDartPlugin
      ios:
        pluginClass: WireguardDartPlugin
        sharedDarwinSource: true
      linux:
        pluginClass: WireguardDartPlugin
      macos:
        pluginClass: WireguardDartPlugin
        sharedDarwinSource: true
      windows:
        pluginClass: WireguardDartPluginCApi
